apiVersion: apps/v1
kind: Deployment
metadata:
  name: text
spec:
  selector:
    matchLabels:
      app: text
  template:
    metadata:
      labels:
        app: text
    spec:
      containers:
      - name: text
        image: olehmydynskyi/text:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: text
spec:
  type: LoadBalancer
  selector:
    app: text
  ports:
  - port: 5050
    targetPort: 80

