apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-home-page
spec:
  selector:
    matchLabels:
      app: python-home-page
  template:
    metadata:
      labels:
        app: python-home-page
    spec:
      containers:
      - name: python-home-page
        image: olehmydynskyi/python-home:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: python-home-page
spec:
  type: LoadBalancer
  selector:
    app: python-home-page
  ports:
  - port: 4040
    targetPort: 7070

