apiVersion: apps/v1
kind: Deployment
metadata:
  name: table
spec:
  selector:
    matchLabels:
      app: table
  template:
    metadata:
      labels:
        app: table
    spec:
      containers:
      - name: table
        image: olehmydynskyi/table:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: table
spec:
  type: LoadBalancer
  selector:
    app: table
  ports:
  - port: 6060
    targetPort: 80

